/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodeChallengeFeatureFlagFormRouteImport } from './routes/code-challenge.feature-flag-form'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeChallengeFeatureFlagFormRoute =
  CodeChallengeFeatureFlagFormRouteImport.update({
    id: '/code-challenge/feature-flag-form',
    path: '/code-challenge/feature-flag-form',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/code-challenge/feature-flag-form': typeof CodeChallengeFeatureFlagFormRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/code-challenge/feature-flag-form': typeof CodeChallengeFeatureFlagFormRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/code-challenge/feature-flag-form': typeof CodeChallengeFeatureFlagFormRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/code-challenge/feature-flag-form'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/code-challenge/feature-flag-form'
  id: '__root__' | '/' | '/code-challenge/feature-flag-form'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodeChallengeFeatureFlagFormRoute: typeof CodeChallengeFeatureFlagFormRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-challenge/feature-flag-form': {
      id: '/code-challenge/feature-flag-form'
      path: '/code-challenge/feature-flag-form'
      fullPath: '/code-challenge/feature-flag-form'
      preLoaderRoute: typeof CodeChallengeFeatureFlagFormRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodeChallengeFeatureFlagFormRoute: CodeChallengeFeatureFlagFormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
